blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://docs.turboeth.xyz/overview
    about: For more detailed guide follow TurboETH docs
  - name: Join our Discord community
    url: https://discord.gg/U4jy7Xfh76
    about: Participate in our thriving community of contributors, users, and supporters.
  - name: Twitter
    url: https://discord.gg/U4jy7Xfh76
    about: Participate in our thriving community of contributors, users, and supporters.
